name: Import

on:
  push:

jobs:
  import:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: latest

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "import_here/*.txt"

      - name: Import files
        if: steps.check_files.outputs.files_exists == 'true'
        run: bundle exec bin/import

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          commit_message: Auto import clippings
          file_pattern: 'clippings.yml imports/*.yml import_here/*.txt'
