name: Import and Publish

on:
  push:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: latest

      - name: Check for new files to import
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "import_here/*.txt"

      - name: Import files
        if: steps.check_files.outputs.files_exists == 'true'
        run: bundle exec bin/import

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          commit_message: Auto import clippings
          file_pattern: 'clippings.yml import_here/*.txt'

      - name: Jekyll build
        run: bundle exec jekyll build --trace --profile

      - name: Push to gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          enable_jekyll: false
